/*
 * Config Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using configmanager.Model;
using configmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace configmanager.Test.Model
{
    /// <summary>
    ///  Class for testing BulkSetConfigsRequestConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BulkSetConfigsRequestConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BulkSetConfigsRequestConfig
        //private BulkSetConfigsRequestConfig instance;

        public BulkSetConfigsRequestConfigTests()
        {
            // TODO uncomment below to create an instance of BulkSetConfigsRequestConfig
            //instance = new BulkSetConfigsRequestConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BulkSetConfigsRequestConfig
        /// </summary>
        [Fact]
        public void BulkSetConfigsRequestConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" BulkSetConfigsRequestConfig
            //Assert.IsType<BulkSetConfigsRequestConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'BusinessDomain'
        /// </summary>
        [Fact]
        public void BusinessDomainTest()
        {
            // TODO unit test for the property 'BusinessDomain'
        }
    }
}
