/*
 * configmanager/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using configmanager.Model;
using configmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace configmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ConfigmanagerConfigResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfigmanagerConfigResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfigmanagerConfigResponse
        //private ConfigmanagerConfigResponse instance;

        public ConfigmanagerConfigResponseTests()
        {
            // TODO uncomment below to create an instance of ConfigmanagerConfigResponse
            //instance = new ConfigmanagerConfigResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigmanagerConfigResponse
        /// </summary>
        [Fact]
        public void ConfigmanagerConfigResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConfigmanagerConfigResponse
            //Assert.IsType<ConfigmanagerConfigResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
