/*
 * Config Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using configmanager.Model;
using configmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace configmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ConfigmanagerGetTenantIdByCodeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfigmanagerGetTenantIdByCodeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfigmanagerGetTenantIdByCodeRequest
        //private ConfigmanagerGetTenantIdByCodeRequest instance;

        public ConfigmanagerGetTenantIdByCodeRequestTests()
        {
            // TODO uncomment below to create an instance of ConfigmanagerGetTenantIdByCodeRequest
            //instance = new ConfigmanagerGetTenantIdByCodeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigmanagerGetTenantIdByCodeRequest
        /// </summary>
        [Fact]
        public void ConfigmanagerGetTenantIdByCodeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConfigmanagerGetTenantIdByCodeRequest
            //Assert.IsType<ConfigmanagerGetTenantIdByCodeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
    }
}
