/*
 * configmanager/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using configmanager.Model;
using configmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace configmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ConfigmanagerBulkSetConfigsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfigmanagerBulkSetConfigsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfigmanagerBulkSetConfigsRequest
        //private ConfigmanagerBulkSetConfigsRequest instance;

        public ConfigmanagerBulkSetConfigsRequestTests()
        {
            // TODO uncomment below to create an instance of ConfigmanagerBulkSetConfigsRequest
            //instance = new ConfigmanagerBulkSetConfigsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigmanagerBulkSetConfigsRequest
        /// </summary>
        [Fact]
        public void ConfigmanagerBulkSetConfigsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConfigmanagerBulkSetConfigsRequest
            //Assert.IsType<ConfigmanagerBulkSetConfigsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Configs'
        /// </summary>
        [Fact]
        public void ConfigsTest()
        {
            // TODO unit test for the property 'Configs'
        }
    }
}
