/*
 * Config Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using configmanager.Model;
using configmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace configmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ConfigmanagerGetTenantIdByCodeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfigmanagerGetTenantIdByCodeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfigmanagerGetTenantIdByCodeResponse
        //private ConfigmanagerGetTenantIdByCodeResponse instance;

        public ConfigmanagerGetTenantIdByCodeResponseTests()
        {
            // TODO uncomment below to create an instance of ConfigmanagerGetTenantIdByCodeResponse
            //instance = new ConfigmanagerGetTenantIdByCodeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigmanagerGetTenantIdByCodeResponse
        /// </summary>
        [Fact]
        public void ConfigmanagerGetTenantIdByCodeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConfigmanagerGetTenantIdByCodeResponse
            //Assert.IsType<ConfigmanagerGetTenantIdByCodeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
    }
}
