/*
 * configmanager/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using configmanager.Client;
using configmanager.Api;
// uncomment below to import models
//using configmanager.Model;

namespace configmanager.Test.Api
{
    /// <summary>
    ///  Class for testing ConfigManagerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ConfigManagerApiTests : IDisposable
    {
        private ConfigManagerApi instance;

        public ConfigManagerApiTests()
        {
            instance = new ConfigManagerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigManagerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ConfigManagerApi
            //Assert.IsType<ConfigManagerApi>(instance);
        }

        /// <summary>
        /// Test ConfigManagerBulkSetConfigs
        /// </summary>
        [Fact]
        public void ConfigManagerBulkSetConfigsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigmanagerBulkSetConfigsRequest body = null;
            //var response = instance.ConfigManagerBulkSetConfigs(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ConfigManagerGetConfig
        /// </summary>
        [Fact]
        public void ConfigManagerGetConfigTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigmanagerGetConfigRequest body = null;
            //var response = instance.ConfigManagerGetConfig(body);
            //Assert.IsType<ConfigmanagerConfigResponse>(response);
        }

        /// <summary>
        /// Test ConfigManagerGetTenantIdByCode
        /// </summary>
        [Fact]
        public void ConfigManagerGetTenantIdByCodeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigmanagerGetTenantIdByCodeRequest body = null;
            //var response = instance.ConfigManagerGetTenantIdByCode(body);
            //Assert.IsType<ConfigmanagerGetTenantIdByCodeResponse>(response);
        }
    }
}
